=== PatricheloM/Project_Bartender/source/tables/tables.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT table (item*)>
<!ATTLIST table x NMTOKEN #REQUIRED>
<!ATTLIST table y NMTOKEN #REQUIRED>
<!ELEMENT item (name, price, invoice)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT invoice (#PCDATA)>

=== PatricheloM/Project_Bartender/bin/tables/table0K.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "tables.dtd"[]>
<?xml-stylesheet type="text/css" href="tables.css"?>
<table x="142" y="184">
  <item>
    <name>Heineken</name>
    <price>450</price>
    <invoice>Patrik</invoice>
  </item>
  <item>
    <name>Víz</name>
    <price>250</price>
    <invoice>Péter</invoice>
  </item>
  <item>
    <name>Red Bull</name>
    <price>500</price>
    <invoice>János</invoice>
  </item>
  <item>
    <name>nachos</name>
    <price>250</price>
    <invoice>János</invoice>
  </item>
</table>

=== PatricheloM/Project_Bartender/source/tables/table0K.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "tables.dtd"[]>
<?xml-stylesheet type="text/css" href="tables.css"?>
<table x="200" y="276">
  <item>
    <name>HEINEKEN</name>
    <price>450</price>
    <invoice>PATRIK</invoice>
  </item>
  <item>
    <name>VÍZ</name>
    <price>250</price>
    <invoice>1</invoice>
  </item>
  <item>
    <name>NACHOS</name>
    <price>600</price>
    <invoice>1</invoice>
  </item>
  <item>
    <name>TÁTRA TEA 52</name>
    <price>900</price>
    <invoice>PATRIK</invoice>
  </item>
  <item>
    <name>TÁTRA TEA 52</name>
    <price>900</price>
    <invoice>PATRIK</invoice>
  </item>
</table>
